[project]
name = "simple-text-editor"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["customtkinter>=5.2.2"]
[[tool.mypy.overrides]]
module = ["customtkinter.*"]
follow_untyped_imports = true
